linters:
  eslint:
    # indicate where is the config file for stylelint
    config: './eslint.config'

# add the files here you want to be ignored by stylelint
files:
  ignore:
      - 'dist/*'
      - 'js/semantic.min.js'
      - '.eslintrc.js'